# Site settings
title: devengines
email: mail.devengines@gmail.com
description: "My portfolio site"
baseurl: "/portfolio-site"
url: ""

twitter_username:
github_username:

# Build settings
markdown: kramdown
